spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tracker_calories
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQLDialect
